---

# -m <manager ip>     Manager IP Address.
# -p <port>           Manager port (default 1515).
# -A <agent name>     Agent name (default is the hostname).
# -D <OSSEC Dir>      Location where OSSEC is installed.
- name: "register agent with server"
  shell: /var/ossec/bin/agent-auth -m {{ ossec_server_ip }} -p 1515
  args:
    creates: /var/ossec/etc/client.keys

- name: "start ossec agent"
  shell: /var/ossec/bin/ossec-control start
