---

- name: centos - build folder
  file:
    state=directory
    path={{ ossec_build_folder }}

- name: centos - check if already installed
  stat: path=/var/ossec/bin/ossec-control
  ignore_errors: yes
  register: ossec_installed

- name: CentOS - download setup
  get_url:
    url=https://www.atomicorp.com/installers/atomic
    dest={{ ossec_build_folder }}/atomic
  when: not ossec_installed.stat.exists

- name: centos - make executable 
  file:
    path={{ ossec_build_folder }}/atomic
    mode=0755

- name: centos - add correct yum repo
  shell: "{{ ossec_build_folder }}/atomic"
  args:
    chdir:  "{{ ossec_build_folder }}"
  environment:
    NON_INT: yes
  ignore_errors: yes
  when: not ossec_installed.stat.exists

- name: CentOS - Install OSSEC Server Package
  yum:
    pkg={{ item }}
    state=present
    update_cache=yes
  with_items:
    - ossec-hids
    - ossec-hids-server
  when: (ossec_server or ossec_local)

- name: CentOS - Install OSSEC Agent 
  yum:
    pkg={{ item }}
    state=present
    update_cache=yes
  with_items:
    - ossec-hids
    - ossec-hids-client
  when: (not ossec_server and not ossec_local)
