---

- name: install_source - check if already installed
  stat: path=/var/ossec/bin/ossec-control
  ignore_errors: yes
  register: ossec_installed

- name: install_source - download source
  get_url:
    url={{ ossec_source_url }}
    dest={{ ossec_build_folder }}/{{ ossec_source_filename }}
  when: not ossec_installed.stat.exists

- name: install_source - unarchive source
  unarchive:
    src={{ ossec_build_folder }}/{{ ossec_source_filename }}
    dest={{ ossec_build_folder }}/{{ ossec_source_filename|replace('.tar.gz', '') }}
    copy=no
  when: not ossec_installed.stat.exists

- set_fact:
    ossec_build_folder_source: "{{ ossec_build_folder }}/{{ ossec_source_filename|replace('.tar.gz', '') }}"
  when: not ossec_installed.stat.exists

- name: install_source - unattended install config
  tags:
    - install
  template:
    src=preloaded-vars.conf.j2
    dest="{{ ossec_build_folder_source }}/etc/preloaded-vars.conf"
  when: not ossec_installed.stat.exists

- name: install_source - compile and install
  shell: ./install.sh
  args:
    chdir: "{{ ossec_build_folder_source }}"
    creates: /var/ossec/bin/ossec-control
  when: not ossec_installed.stat.exists
