---
- name: depend
  include: depend.yml
  tags:
    - install

- name: install debian package
  include: install_debian.yml
  tags:
    - install
  when: (ansible_os_family == "Debian" and not ossec_from_source)

- name: install from source
  include: install_source.yml
  tags:
    - install
  when: (ansible_os_family == "RedHat" or ossec_from_source)

- name: configure server
  include: config_server.yml
  tags:
    - config
  when: (ossec_server and not ossec_local)

- name: configure agent
  include: config_agent.yml
  tags:
    - config
  when: (not ossec_server and not ossec_local)
