---
- name: preinstall - create folder
  file:
    state=directory
    path=/var/ossec/etc/

- name: preinstall - centos depend
  yum:
    name=libselinux-python
    state=present
  when: ansible_os_family == "RedHat"

- name: preinstall - unattended install config
  tags:
    - install
  template:
    src=preloaded-vars.conf.j2
    dest=/var/ossec/etc/preloaded-vars.conf

- name: centos - build folder
  file:
    state=directory
    path={{ ossec_build_folder }}

